version: '3.5'
services:
    postgres:
        image: postgres:12
        environment: 
            POSTGRES_USER: magic_formula
            POSTGRES_DB: magic_formula
            POSTGRES_PASSWORD: magic_formula
        volumes:
            - ./db/postgres-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
