version: '3.5'
services:
    rest_api:
        build: .
        ports: 
            - '8000:8000'

    postgres:
        image: postgres:12
        environment: 
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        env_file:
            - .env
        ports:
            - '5050:80'
volumes:
    postgres-data: